### PR TITLE
fix: serde serialization of Constraint Violation Exception

### PR DESCRIPTION
**Pull request by sdelamo**
Close https://github.com/micronaut-projects/micronaut-problem-json/issues/178

see https://github.com/micronaut-projects/micronaut-problem-json/pull/193

### CODE REVIEW

**Comment by yawkat** [comment]
i think it's better to just make a second class like ThrowableProblemWithoutStacktrace, but for constraint violations. that way, users can still include the stack trace if they want.

**Comment by sdelamo** [comment]
> i think it's better to just make a second class like ThrowableProblemWithoutStacktrace, but for constraint violations. that way, users can still include the stack trace if they want.

I took this approach because there [seems to be an issue with serde, JsonUnwrapp JsonIgnoreProperties and implementing an interface.](https://github.com/micronaut-projects/micronaut-problem-json/pull/196).

**Review by timyates — APPROVED** [review]

**Comment by yawkat** [comment]
yes that looks like a bug, but you can use `@Introspected` until it's fixed, no? it's not more problematic than ThrowableProblemWithoutStacktrace already is

**Comment by sdelamo** [comment]
I am going to merge this PR and do a patch release. This at  least solves rendering `ConstraintViolationException` which a really common thing. Moreover, you probably never care to output the exception message for such a exception since you have information in the violations parameter. 

Once the bug is fixed: https://github.com/micronaut-projects/micronaut-problem-json/pull/196 I can remove the extra `else if` statement.

**Pull request merged**
