### PR TITLE
Fixes in gradle script dependencies. Get versions from versions catalogs

### PR DESCRIPTION
**Pull request by altro3**

### CODE REVIEW

**Comment by altro3** [comment]
@sdelamo Please, review it

**Review by sdelamo — CHANGES_REQUESTED** [review]
rename `build-logic` to `buildSrc`. Please, don't change the conventions we use in every module.

**Comment by altro3** [comment]
I also thought that everything should be the same everywhere, but then why is this folder called build-logic in micronaut openapi?

**Comment by sdelamo** [comment]
> I also thought that everything should be the same everywhere, but then why is this folder called build-logic in micronaut openapi?

I don't know. We have more than 60 modules. Please revert this PR to use `buildSrc` as we do in every other module. Maybe we should change openapi to use `buidlSrc` not the rest of the modules to mirror openapi.

**Comment by altro3** [comment]
@sdelamo Hi! Sorry, forgot about this PR. But now I'm more informated about build plugins in gradle. Look to this answer:

https://discuss.gradle.org/t/buildsrc-vs-build-logic/46708

In general, when you create a new project on Gradle via the command line (or migrate a project from Maven), Gradle automatically creates a build-logic directory. All this means is that after the release of version 8, their logic changed a little and buildSrc is now 99% replaced with build-logic or another directory

**Pull request closed without merging**
